# Generated by Django 3.1.7 on 2023-06-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0002_remove_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='user',
        ),
    ]
