# Generated by Django 3.1.7 on 2023-06-20 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0005_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(blank=True, null=True, to='myWorkout.Workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 20, 18, 55, 630167, tzinfo=utc)),
        ),
    ]
