# Generated by Django 3.1.7 on 2023-06-22 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0006_auto_20230620_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 19, 8, 54, 993089, tzinfo=utc)),
        ),
    ]
