# Generated by Django 3.1.7 on 2023-06-22 19:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0008_auto_20230622_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='workout_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myWorkout.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 19, 46, 50, 583746, tzinfo=utc)),
        ),
    ]
