# Generated by Django 3.1.7 on 2023-06-24 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0010_auto_20230622_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='program_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myWorkout.program'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 16, 45, 3, 627896, tzinfo=utc)),
        ),
    ]
