# Generated by Django 3.1.7 on 2023-06-24 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myWorkout', '0011_auto_20230624_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 24, 16, 46, 28, 943199, tzinfo=utc)),
        ),
    ]
